alias ls='ls -F'

# To prevent stupidity
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ln='ln -i'

# enable color support of ls in Ubuntu and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

function ql()
{
	qlmanage -p "$@" >& /dev/null
}

function ackp {
    ack $@ --pager='less -R'
}

function hgroot {
    MYCWD=$(pwd)
    until [ -d ${MYCWD}/.hg ]; do
      MYCWD=$(dirname ${MYCWD})
      if [ "${MYCWD}" == "/" ]; then
        exit 1;
      fi
    done
    echo ${MYCWD}
}

function gohere() {
    export GOPATH=$(pwd)
}

LOCAL_ALIASES="${HOME}/.bash_aliases_local"
if [ -e ${LOCAL_ALIASES} ]; then
	source ${LOCAL_ALIASES}
fi
